// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vifgyyereuylhycvyjcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpZmd5eWVyZXV5bGh5Y3Z5amNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExNTgzOTcsImV4cCI6MjA1NjczNDM5N30.OUq-iR8fIGO3CyFpF-q1Gj_9acmC5oOZ3EYRIDREUbo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);